server:
  port: 8081
  
  
spring:
  thymeleaf:
    mode: HTML5
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false

  datasource:
    url: jdbc:h2:file:~/tmp/testdb;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password: tlseotn1@

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
   console:
     enabled: true
     path: /console

  devtools:
    restart:
      enabled: true
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
   